services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=videojuegos
    command: ["npx", "nodemon", "src/app.js"]
  postgres:
    image: postgres:17
    ports:
      - 5432:5432
    volumes:
      - ./.volumes/postgres/data:/var/lib/postgresql/data/
      - ./base_de_datos:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=videojuegos
  frontend:
    image: nginx:stable
    container_name: frontend
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "8080:80"